### ISSUE TITLE
ValueError: host not found: Name or service not known with torchelastic

### ISSUE THREAD

**Issue by mckunkel** [pytorch/elastic#113]
### Question
I have a piece of code that runs with torch.distributed.launch.
I modified the code to launch via torchelastic.distributed.launch in the prescribed manner as seen in the examples from the github page and the official pytorch documetation.

However whenI run the code I get the following error

`[INFO] 2020-07-20 14:09:18,781 launch: Running torchelastic.distributed.launch with args: ['/usr/local/lib/python3.6/dist-packages/torchelastic/distributed/launch.py', '--nproc_per_node=4', '--nnodes=2', '--rdzv_id=0', '--rdzv_endpoint=172.20.74.130:2379', 'tools/train_net_elastic.py', '--config-file', 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml']
INFO 2020-07-20 14:09:18,785 Etcd machines: ['http://0.0.0.0:2379']
[INFO] 2020-07-20 14:09:18,789 launch: Using nproc_per_node=4.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[INFO] 2020-07-20 14:09:19,358 api: [default] starting workers for function: wrapper_fn
[INFO] 2020-07-20 14:09:19,358 api: [default] Rendezvous'ing worker group
INFO 2020-07-20 14:09:19,358 Attempting to join next rendezvous
INFO 2020-07-20 14:09:19,362 Observed existing rendezvous state: {'status': 'final', 'version': '18', 'participants': [0, 1], 'keep_alives': ['/torchelastic/p2p/run_0/rdzv/v_18/rank_1', '/torchelastic/p2p/run_0/rdzv/v_18/rank_0'], 'num_workers_waiting': 0}
INFO 2020-07-20 14:09:19,439 Added self to waiting list. Rendezvous full state: {"status": "final", "version": "18", "participants": [0, 1], "keep_alives": ["/torchelastic/p2p/run_0/rdzv/v_18/rank_1", "/torchelastic/p2p/run_0/rdzv/v_18/rank_0"], "num_workers_waiting": 1}
INFO 2020-07-20 14:09:19,441 Keep-alive key /torchelastic/p2p/run_0/rdzv/v_18/rank_1 is not renewed.
INFO 2020-07-20 14:09:19,441 Rendevous version 18 is incomplete. 
INFO 2020-07-20 14:09:19,441 Attempting to destroy it.
INFO 2020-07-20 14:09:19,442 Destroyed rendezvous version 18 successfully.
INFO 2020-07-20 14:09:19,442 Previously existing rendezvous state changed. Will re-try joining.
INFO 2020-07-20 14:09:19,442 Attempting to join next rendezvous
INFO 2020-07-20 14:09:19,447 New rendezvous state created: {'status': 'joinable', 'version': '19', 'participants': []}
INFO 2020-07-20 14:09:19,535 Joined rendezvous version 19 as rank 0. Full state: {'status': 'joinable', 'version': '19', 'participants': [0]}
INFO 2020-07-20 14:09:19,535 Waiting for remaining peers.
INFO 2020-07-20 14:09:27,463 All peers arrived. Confirming membership.
INFO 2020-07-20 14:09:27,492 Waiting for confirmations from all peers.
INFO 2020-07-20 14:09:27,527 Rendezvous version 19 is complete. Final state: {'status': 'final', 'version': '19', 'participants': [0, 1], 'keep_alives': ['/torchelastic/p2p/run_0/rdzv/v_19/rank_0', '/torchelastic/p2p/run_0/rdzv/v_19/rank_1'], 'num_workers_waiting': 0}
INFO 2020-07-20 14:09:27,527 Creating EtcdStore as the c10d::Store implementation
[INFO] 2020-07-20 14:09:27,593 api: [default] Rendezvous complete for workers.
Result:
        restart_count=0
        group_rank=0
        group_world_size=2
        rank stride=4
        assigned global_ranks=[0, 1, 2, 3]
        master_addr=XXXXX
        master_port=55673

[INFO] 2020-07-20 14:09:27,593 api: [default] Starting worker group
Traceback (most recent call last):
  File "tools/train_net_elastic.py", line 180, in <module>
    launch_elastic()
  File "tools/train_net_elastic.py", line 170, in launch_elastic
    dist.init_process_group(backend="nccl")
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Name or service not known
` 
my other node has the following

`python -m torchelastic.distributed.launch --nproc_per_node=4 --nnodes=2 --rdzv_id=0 --rdzv_endpoint=$ETCD_SERVICE_SERVICE_HOST:$ETCD_SERVICE_SERVICE_PORT tools/train_net_elastic.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml
[INFO] 2020-07-20 14:09:26,796 launch: Running torchelastic.distributed.launch with args: ['/usr/local/lib/python3.6/dist-packages/torchelastic/distributed/launch.py', '--nproc_per_node=4', '--nnodes=2', '--rdzv_id=0', '--rdzv_endpoint=172.20.74.130:2379', 'tools/train_net_elastic.py', '--config-file', 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml']
INFO 2020-07-20 14:09:26,801 Etcd machines: ['http://0.0.0.0:2379']
[INFO] 2020-07-20 14:09:26,808 launch: Using nproc_per_node=4.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[INFO] 2020-07-20 14:09:27,369 api: [default] starting workers for function: wrapper_fn
[INFO] 2020-07-20 14:09:27,370 api: [default] Rendezvous'ing worker group
INFO 2020-07-20 14:09:27,370 Attempting to join next rendezvous
INFO 2020-07-20 14:09:27,375 Observed existing rendezvous state: {'status': 'joinable', 'version': '19', 'participants': [0]}
INFO 2020-07-20 14:09:27,462 Joined rendezvous version 19 as rank 1. Full state: {'status': 'frozen', 'version': '19', 'participants': [0, 1], 'keep_alives': []}
INFO 2020-07-20 14:09:27,462 Waiting for remaining peers.
INFO 2020-07-20 14:09:27,464 All peers arrived. Confirming membership.
INFO 2020-07-20 14:09:27,528 Waiting for confirmations from all peers.
INFO 2020-07-20 14:09:27,529 Rendezvous version 19 is complete. Final state: {'status': 'final', 'version': '19', 'participants': [0, 1], 'keep_alives': ['/torchelastic/p2p/run_0/rdzv/v_19/rank_0', '/torchelastic/p2p/run_0/rdzv/v_19/rank_1'], 'num_workers_waiting': 0}
INFO 2020-07-20 14:09:27,529 Creating EtcdStore as the c10d::Store implementation
[INFO] 2020-07-20 14:09:27,593 api: [default] Rendezvous complete for workers.
Result:
        restart_count=0
        group_rank=1
        group_world_size=2
        rank stride=4
        assigned global_ranks=[4, 5, 6, 7]
        master_addr=XXX
        master_port=55673
[INFO] 2020-07-20 14:09:27,593 api: [default] Starting worker group
Traceback (most recent call last):
  File "tools/train_net_elastic.py", line 180, in <module>
    launch_elastic()
  File "tools/train_net_elastic.py", line 170, in launch_elastic
    dist.init_process_group(backend="nccl")
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Name or service not known
`

My etcd works for the examples in given, and I cannot seem to find the source of this on Google, StackExchange or as an Issue on this repository.

I have initialized my distribution as
`        dist.init_process_group(backend="nccl", init_method="env://")
`

Could you point me in the correct direction for debugging this?

**Comment by kiukchung** [comment]
Thanks for reporting. Seems like a routing issue. torchelastic uses node rank 0's FQDN as the `MASTER_ADDR`. On the node you are seeing this issue can you validate that you are able to ping the `MASTER_ADDR`?

**Comment by mckunkel** [comment]
Thanks for the prompt reply. It seemed that my etcd server was not setup properly. I switched to a different version and it ran, but now I am facing another issue with -shm (shared memory) in torchelastic.distributed using kubernetes, that I haven't seen (same code base, same dockerfile + torch elastic) using torch.distributed
I am hunting the this new problem.
