### ISSUE TITLE
Wrapping elastic-job kubernetes in initcontainer

### ISSUE THREAD

**Issue by mckunkel** [pytorch/elastic#114]
After successfully running a ElasticJob on kubernetes, I would like to move the contents of an output folder to another location. For instance, my kubernetes cluster is actually EKS and I want to put output to S3. 
I would usually wrap my Job/Deployment/Pod/.. such that the container moves the value of an initcontainer which actually performs the training, i.e.

`apiVersion: v1 

kind: Pod
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup : worker-group
          containers:
          - name: output-data
            image: XXX.ecr.us-XXX-X.amazonaws.com/side_car
            command: ["aws", "s3" ,"cp", "/output" ,"s3://OUTPUT", "--recursive"]
            volumeMounts:
            - name: output
              mountPath: /output
          initContainers:
          - name: worker
            image: XXX-XXX-1.amazonaws.com/eks/pytorch:detectron2
            imagePullPolicy: Always
            args:
              - "--nproc_per_node=4"
              - "/code/tools/train_net_elastic.py"
            resources:
              limits:
                nvidia.com/gpu: 4
          ...
          ...
`
Here my container just utilizes a side-car that does aws s3 copying and the initcontaiiner would be the trainer populating the /output directory.

However since the apiVersion: elastic.pytorch.org/v1alpha1 actually gives the
`    Args:

      --rdzv_backend=etcd
      --rdzv_endpoint=etcd-service:2379
      --rdzv_id=em-tech-maskrcnn
      --nnodes=1:2`
to the container and not an initcontainer, I am seeking guidance on how to work around this obstacle.

**Comment by kiukchung** [comment]
Could you upload the output directly from the trainers (as the last step in the script)? If you need one worker to upload then you could have rank 0 upload the output.

**Comment by mckunkel** [comment]
I could, but I really rather keep the AWS:EKS/GCP:GKE calls native to their platform.
Can the entrypoint for elasticjob be modified such that it takes a script first then passes the args?
Then I can wrap everything into a bash script, throw it into a config map and be done.

I tried running it all through a bash scrip, but the launch didn't like it.

**Comment by kiukchung** [comment]
I see, yea if you are working with multiple cloud providers, what you are trying to do makes sense.

>> For other modeling libraries, I usually only have to create a service in kubernetes and have all workers point to worker 0; Can something like this be done with the etcd service without elasticjob? I have tried, but torchelastic couldn't find the host.

Can you elaborate on the above (I think this was your initial question about the host not being reachable)? There is nothing specific to routing in torchelastic. If you can ping a host:port from one node, then you should be able to create a socket to the destination host in your training script.

>> Can the entrypoint for elasticjob be modified such that it takes a script first then passes the args?

Yes (with a caveat) the we actually just use the ENTRYPOINT of the docker image that you specify in the pod spec yaml so you can build your own image with the ENTRYPOINT of your choice, the controller will however set some default args (`--rdzv_backend, --rdzv_endpoint, --rdzv_id, --nnodes` - see https://github.com/pytorch/elastic/blob/master/kubernetes/controllers/pod.go#L116) so as long as your entrypoint script is able to deal with those and pass them along to torchelastic, you can specify your own entrypoint script.

**Comment by mckunkel** [comment]
I ended up creating a bash script to take the arguments for torch.elastic and run my pre and post training commands inside this script. I generalized the script enough to work on multiple cloud providers. 
Thanks for the advice.
