### ISSUE TITLE
Support PyTorch 1.8, TorchVision 0.9.0 and TorchAduio 0.8.0

### ISSUE THREAD

**Issue by DavidSpek** [pytorch/elastic#142]
## 🐛 Bug

I am getting a Pip error when trying to install TorchElastic 0.2.2 with the recently released PyTorch 1.8. Seems like a small patch update will be needed to fix the requirement issue. 
https://github.com/pytorch/pytorch/releases/tag/v1.8.0

**Comment by DavidSpek** [comment]
@kiukchung Should I open a PR to change https://github.com/pytorch/elastic/blob/master/requirements.txt to `toch>=1.8.0`? Is that the cause of the current incompatibility with torch 1.8.

**Comment by kiukchung** [comment]
@DavidSpek - thanks for reporting. Could you provide the details of the pip error?

**Comment by DavidSpek** [comment]
@kiukchung I'm very sorry but this seems to have been an error on my part. I was trying to build a docker image and the message made it seem like torchelastic had a dependency issue with torch. The problem was actually that torchelastic with the dependency torch>=1.8.0dev was conflicting with a package that does not yet support torch 1.8. Thank you for the quick response and again sorry for the incorrect issue.

**Comment by kiukchung** [comment]
FWIW the pytorch-1.8 docker images already have torchelastic installed.

**Comment by DavidSpek** [comment]
@kiukchung Thanks for the info. The images I am working on are the ones that will ship with the upcoming Kubeflow release, and PyTorch and TensorFlow use a common base image I made so using the PyTorch docker image isn't an option. But it's good to know it is included for other use cases.

**Comment by kiukchung** [comment]
ah gotcha, btw torchelastic is being upstreamed to pytorch (see https://github.com/pytorch/pytorch/issues/50621), we are about 70% through with the code move (this is why our CI tests are broken at the moment). torchelastic will be natively available through the pytorch package starting torch-1.9.

**Comment by DavidSpek** [comment]
Awesome, I think that move makes a lot of sense.
