### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.distributed.elastic'

### ISSUE THREAD

**Issue by GwangsooHong** [pytorch/elastic#145]
## 🐛 Bug

Component (check all that applies):
 * [ ] `state api`
 * [ ] `train_step api`
 * [ ] `train_loop`
 * [ ] `rendezvous`
 * [ ] `checkpoint`
 * [ ] `rollback`
 * [ ] `metrics`
 * [ ] `petctl`
 * [ ] `examples`
 * [ ] `docker`
 * [x] other
 

## To Reproduce

1. git clone https://github.com/pytorch/elastic
2. cd elastic; docker build -t elastic:1.5-py3 -f Dockerfile . 
3. docker run -it --runtime=nvidia -v $(pwd):/workspace elastic:1.5-py3
4. python -m torchelastic.distributed.launch
--> 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/torchelastic/torchelastic/distributed/launch.py", line 227, in <module>
    import torch.distributed.elastic.rendezvous.registry as rdzv_registry
ModuleNotFoundError: No module named 'torch.distributed.elastic'

## Expected behavior
No error 

## Environment

 - torchelastic version (e.g. 0.1.0rc1): 0.2.2
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS
 - How you installed torchelastic (`conda`, `pip`, source, `docker`): pip install torchelastic
 - Docker image and tag (if using docker): https://github.com/pytorch/elastic/blob/master/Dockerfile
 - Build command you used (if compiling from source):
 - Git commit (if installed from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Execution environment (on-prem, aws, etc):
 - Any other relevant information:

**Comment by GwangsooHong** [comment]
I changed dockerfile from `FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime` to `FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime`. I also got a ModuleNotFoundError: No module named 'torch.distributed.elastic' error.

**Comment by kiukchung** [comment]
Hi, the docker image: `pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime` already has torchelastic installed, no need to build a separate docker. Hope that helps.

**Comment by GwangsooHong** [comment]
Hi, I checked the `torchelastic` installed but got a no module `torch.distributed.elastic` error.  Do I need additional installation?

For reproduction, I ran the `docker run -it --runtime=nvidia -v $(pwd):/workspace pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime` 
and 
```
root@a85c2c1be459:/workspace# python
Python 3.8.8 (default, Feb 24 2021, 21:46:12)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchelastic
>>> import torch.distributed.elastic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch.distributed.elastic'
```

**Comment by kiukchung** [comment]
torch.distributed.elastic does not exist in torch1.8. torchelastic is under the torchelastic module.
