### ISSUE TITLE
Out of Data documentation

### ISSUE THREAD

**Issue by Godricly** [pytorch/elastic#147]
## 📚 Documentation
1. In the documentation, there is a submodule `multiprocessing`. But I can't find it.

## Link
https://pytorch.org/elastic/0.2.2/multiprocessing.html#torchelastic.multiprocessing.start_processes

## What does it currently say?
```
from torchelastic.multiprocessing import Redirect, start_processes
```

## What should it say?
I don't know. I can't find the multiprocessing module.

### Others
1.pip can't install torchelastic==0.2.2
 I used pip to install torchelastic. But I can only install the v0.2.0 version.
2. Documentation version switching
   The documents can not be switched between difference versions.

### my ENV 
generated with https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
```
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti

Nvidia driver version: 440.64
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.8.1
[pip3] torchelastic==0.2.0
[pip3] torchvision==0.8.1
[conda] Could not collect

```

**Comment by Godricly** [comment]
Update:
torchelastic requires python3.8+... 
Now I can download v0.2.2 version.

**Comment by Godricly** [comment]
```
from torchelastic.multiprocessing import Redirect
```
This one still fails in v0.2.2
```

In [2]: from torchelastic.multiprocessing import Redirect
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-388d01fa739d> in <module>
----> 1 from torchelastic.multiprocessing import Redirect

ImportError: cannot import name 'Redirect' from 'torchelastic.multiprocessing' 
```

**Comment by kiukchung** [comment]
Thank you for the report! Yes indeed this is an error in the documentation. It should read

```
from torchelastic.multiprocessing import Std # not Redirect
```

FWIW, torchelastic has been upstreamed to pytorch (under `torch.distributed.elastic`) the new location of this module is:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/elastic/multiprocessing/__init__.py#L74

We will update the documentation with the upcoming pytorch 1.9 release. Feel free to reopen if you run into other related issues.

**Comment by Godricly** [comment]
Does the pytorch1.9 require python3.8?
