### ISSUE TITLE
Out of the box Kubernetes documentation/support

### ISSUE THREAD

**Issue by ewhal** [pytorch/elastic#16]
## Description
Would be best to provide kubernetes examples and docs as to make this not AWS specific. 
K8s with auto-scaling could also potentially simplify any of the aws specific code and allow for greater options of pipelines in the future

**Comment by kiukchung** [comment]
Thank you for the feedback! Yes, k8 support is definitely on our radar as a fast-follow feature. We decided to support vanilla ec2 for our rc release as an example to ensure that torchelastic setup is transferable to as many runtime environments without being tied to a specific provider. Stay tuned!
