### ISSUE TITLE
 Why petctl name for the AWS tool?

### ISSUE THREAD

**Issue by kit1980** [pytorch/elastic#18]
I'm just wondering, why `petctl` name for the AWS tool? Is it an abbreviation or maybe it has some other meaning?

**Comment by kiukchung** [comment]
`pet` stands for PyTorch Elastic Trainer, which was the code name for torchelastic while it was being developed. `ctl` stands for Control, and commonly used as a suffix for CLI tools.

As for `petctl` currently being AWS only. We initially shipped with AWS support but plan to expand to other platforms. When this happens it will make sense to pull `petctl` out of the `aws` directory onto its own.
