### ISSUE TITLE
Job fails when the number of dataset are not exactly divided by the batch size

### ISSUE THREAD

**Issue by Jeffwan** [pytorch/elastic#26]
## ❓ Questions and Help

I am trying resnet101 and imagenet [example](https://github.com/pytorch/elastic/tree/master/examples/imagenet) with tiny imagenet dataset (https://tiny-imagenet.herokuapp.com/ ).

I notice there's a failure in the customized sampler https://github.com/pytorch/elastic/blob/f5a0968aa3842a1f29e1d36aee59cb2acff5cfaa/torchelastic/utils/data/elastic_distributed_sampler.py#L38-L43

I have two questions
1. Should I specify `dropLast=True` in DataLoader initialization?
https://github.com/pytorch/elastic/blob/f5a0968aa3842a1f29e1d36aee59cb2acff5cfaa/examples/imagenet/main.py#L182-L189

2. If `start_index == len(dataset)`, it should finish the current epoch. Should we change the condition to `start_index > len(dataset)`? 

https://github.com/pytorch/elastic/blob/f5a0968aa3842a1f29e1d36aee59cb2acff5cfaa/torchelastic/utils/data/elastic_distributed_sampler.py#L38-L43

```
17:31:57
[INFO] 2020-01-02 01:31:57,146 main: epoch: 0, iteration: 1560, data_idx: 149760
[INFO] 2020-01-02 01:31:57,882 main: epoch: 0, iteration: 1561, data_idx: 149856
[INFO] 2020-01-02 01:31:58,451 main: epoch: 0, iteration: 1562, data_idx: 149952
[ERROR] 2020-01-02 01:31:58,497 coordinator_p2p: Rank: 0
Error: Start index 100032 should be less than dataset size 100000
ErrorType: <class 'ValueError'>
StackTrace: Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 36, in __next__
return next(self._iter)
File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
index = self._next_index() # may raise StopIteration
File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
return next(self._sampler_iter) # may raise StopIteration
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/torchelastic/train_loop.py", line 96, in train
state, worker_stats = train_step(state)
File "/tmp/fetch_and_run_shqk63yy/main.py", line 285, in train_step
input, target = next(state.data_iter)
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 40, in __next__
self._iter = self._generator_fn(self._epoch)
File "/tmp/fetch_and_run_shqk63yy/main.py", line 177, in _data_iter_generator_fn
start_index=self.data_start_index,
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/elastic_distributed_sampler.py", line 41, in __init__
start_index, len(dataset)
ValueError: Start index 100032 should be less than dataset size 100000
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 36, in __next__
return next(self._iter)
File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
index = self._next_index() # may raise StopIteration
File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
return next(self._sampler_iter) # may raise StopIteration
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/fetch_and_run_shqk63yy/main.py", line 430, in <module>
main()
File "/tmp/fetch_and_run_shqk63yy/main.py", line 411, in main
args.input_path,
File "/tmp/fetch_and_run_shqk63yy/main.py", line 276, in single_trainer
torchelastic.train(coordinator, train_step, state)
File "/opt/conda/lib/python3.6/site-packages/torchelastic/train_loop.py", line 96, in train
state, worker_stats = train_step(state)
File "/tmp/fetch_and_run_shqk63yy/main.py", line 285, in train_step
input, target = next(state.data_iter)
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 40, in __next__
self._iter = self._generator_fn(self._epoch)
File "/tmp/fetch_and_run_shqk63yy/main.py", line 177, in _data_iter_generator_fn
start_index=self.data_start_index,
File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/elastic_distributed_sampler.py", line 41, in __init__
start_index, len(dataset)
ValueError: Start index 100032 should be less than dataset size 100000

```

### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our documentation. Here
are some links that may be helpful:

* [What is torchelastic?](../../README.md)
* [Quickstart on AWS](../../aws/README.md)
* [Usage](../../USAGE.md)
* [Examples](../../examples/README.md)
* API documentation
    * [Overview](../../USAGE.md)
    * [Rendezvous documentation](../../torchelastic/rendezvous/README.md)
    * [Checkpointing documentation](../../torchelastic/checkpoint/README.md)
* [Configuring](../../USAGE.md#configuring)

**Comment by kiukchung** [comment]
Thanks for reporting this issue. Answers in-line:

1. Should I specify drop_last=True in DataLoader initialization?
   Should not be necessary, if you set `drop_last=True` does that get rid of the exception? From the stack-trace I see that your dataset size is 100,000 and batch size is 32, which divides 100,000 (100,000/32 = 3,125). How many workers are you using?

2. If start_index == len(dataset), it should finish the current epoch. Should we change the condition to start_index > len(dataset)?
   `start_index` is zero indexed so the check should be `>=`. For instance, if the dataset has 32 examples, then `start_index==32` is out of bounds since only `0` to `31` are valid indexes for the dataset.

**Comment by Jeffwan** [comment]
> Thanks for reporting this issue. Answers in-line:
> 
> 1. Should I specify drop_last=True in DataLoader initialization?
>    Should not be necessary, if you set `drop_last=True` does that get rid of the exception? From the stack-trace I see that your dataset size is 100,000 and batch size is 32, which divides 100,000 (100,000/32 = 3,125). How many workers are you using?

I am using 2 workers. it should finish 99968 (1562 iterations * 64). Only 32 are left and that's the reason I am considering to drop the last few records.  Even with `drop_last=True`, sampler recalculate start_index and this will fail. 

> 2. If start_index == len(dataset), it should finish the current epoch. Should we change the condition to start_index > len(dataset)?
>    `start_index` is zero indexed so the check should be `>=`. For instance, if the dataset has 32 examples, then `start_index==32` is out of bounds since only `0` to `31` are valid indexes for the dataset.

Make sense. A new Sampler need to be initialized for every `sync` . Let's assume start_index == len(dataset) - 64, dataloader should throw `StopIteration` and epoch += 1? that means we won't see OutOfIndex issue here but not why it doesn't work for me..

**Comment by kiukchung** [comment]
You are correct, I'm looking into why the `start_index` that is passed to the constructor of elastic sampler shoots past the length of the data.

**Comment by raviskolli** [comment]
I ran into the same issue of data_start_index incrementing past the length of the dataset. At the end of an epoch, data loader throws StopIteration exception that is then caught in 
https://github.com/pytorch/elastic/blob/be9201268c357f7e0a9872c3edb75534e67842be/torchelastic/utils/data/cycling_iterator.py#L35-L41

Note that state is not synced at the end of epoch. So start_data_idx is never reset. One way to fix this would be to add reset_data_idx() function to State object and pass it to CyclingIterator along with _data_iter_generate_fn(). CyclingIterator could then call this reset function at the start of each epoch.

**Comment by kiukchung** [comment]
we have a new imagenet example in v0.2.0 feel free to reopen if the issue persists.
