### ISSUE TITLE
[train_loop] Remove usage of `state` returned by `train_step`

### ISSUE THREAD

**Issue by kiukchung** [pytorch/elastic#48]
## Description
Remove assignment and usage (if any) of `state` as the return value from `train_step` in the `train_loop`. 

https://github.com/pytorch/elastic/blob/master/torchelastic/train_loop.py#L29

Should change to 
```
# <omitted...>
worker_stats = train_step(state)
# <omitted...>
```
## Motivation/Background
Currently `train` expects `train_step` to return `state` and `worker_stats`. Returning `state` from `train_step` is unnatural since `state` is expected to be mutable and is the single parameter argument to `train_step(state)`. In most cases users will do something like:

```
def train_step(state):
   # do train (mutates state)
   return state, worker_stats
```
It is both simple and natural for `train_step` to not return `state`.

## Detailed Proposal
See code snippet in description section

## Alternatives
N/A

## Additional context/links
See link in description section

**Comment by drdarshan** [comment]
Hello @kiukchung - shall we close this preemptively since the state will become obsolete?

**Comment by kiukchung** [comment]
closing as v0.2.0 will no longer require users to implement `State` and `train_step`
