### ISSUE TITLE
Provide cluster delete steps

### ISSUE THREAD

**Issue by chauhang** [pytorch/elastic#57]
## Link
https://pytorch.org/elastic/0.1.0rc2/kubernetes.html#clean-up-job

## What does it currently say?
Steps for deleting the cluster are missing. Simply issuing eksctl delete cluster does not work due to EFS mount points added as part of the config

## What should it say?
Provide clear steps for deleting the full cluster, including directions for unmounting EFS mount points

### Why?
Missing from current documentation

**Comment by kiukchung** [comment]
users should refer to the CSP specific manual for cluster teardown steps.
