### ISSUE TITLE
Code structure for kubernetes operator codes

### ISSUE THREAD

**Issue by Jeffwan** [pytorch/elastic#59]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our documentation. Here
are some links that may be helpful:

* [What is torchelastic?](../../README.md)
* [Quickstart on AWS](../../aws/README.md)
* [Usage](../../USAGE.md)
* [Examples](../../examples/README.md)
* API documentation
    * [Overview](../../USAGE.md)
    * [Rendezvous documentation](../../torchelastic/rendezvous/README.md)
    * [Checkpointing documentation](../../torchelastic/checkpoint/README.md)
* [Configuring](../../USAGE.md#configuring)

  
### Question

Hi, I am ready to submit a PR for kubernetes operator. Looking at current structure, we have kubernetes native examples under `/kubernetes` and we also have `examples/` folder. 

Should I put operator codes under `/kubernetes` or a separate `/operator` folder? Should I move kubernetes native examples under `/examples`?

**Comment by drdarshan** [comment]
Hello @Jeffwan, could you please move the operator implementation under the Kubernetes directory? I suppose we can defer moving the example there since it'll look quite different with the operator compared to what you have now. Let me know if you have any other questions. Thanks!

**Comment by Jeffwan** [comment]
@drdarshan Thanks for the guidance. I just file the PR #63 for operator codesand I will file a separate PR to move k8s examples to examples folder.
