### ISSUE TITLE
Add example with checkpointing and recovery for Kubernetes

### ISSUE THREAD

**Issue by chauhang** [pytorch/elastic#74]
## Description
Add a new training example for Kubernetes that demos how to do checkpointing and use it for fault tolerant recovery. 

## Motivation/Background
To make it easier for model developers to benefit from the fault tolerant feature of torchelastic. 

## Detailed Proposal

- Simple example can include checkpoint on every worker node, or just on the rank 0  node and describe how to recover from it.
- On EKS provide steps for how to use with spot instances
- In the documentation, describe the typical strategies that can be used for checkpoint and recovery (eg checkpoint on every node, on the parameter server node, on the rank 0 node etc).

## Additional context/links
For reference see examples in ray cluster on spot instances: https://ray.readthedocs.io/en/latest/tune-distributed.html#example-for-using-spot-instances-aws

**Comment by kiukchung** [comment]
See our new imagenet example for a full e2e script with checkpoint built-in. https://github.com/pytorch/elastic/blob/master/examples/imagenet/main.py#L158
