### ISSUE TITLE
Missing link in PET docs

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/elastic#91]
## 📚 Documentation
There's a missing link on the docs page on this page: https://pytorch.org/elastic/0.2.0.dev0/quickstart.html

## Link
https://pytorch.org/elastic/0.2.0.dev0/quickstart.html

## What does it currently say?
"Learn more about writing your distributed training script here <train_script.html>."

## What should it say?
It should link correctly to train_script.html
### Why?
The correct link does not show up on the docs page

**Comment by kiukchung** [comment]
thanks for reporting! this will be fixed along with our rc1 release tomorrow.

**Comment by kiukchung** [comment]
Fixed in: https://pytorch.org/elastic/0.2.0rc1/quickstart.html

<img width="855" alt="image" src="https://user-images.githubusercontent.com/43595115/79619451-bf9cf700-80c1-11ea-9d1b-5994e5b2bfdf.png">
