### ISSUE TITLE
Kubernetes Konfusion

### ISSUE THREAD

**Issue by mttcnnff** [pytorch/elastic#94]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our documentation. Here
are some links that may be helpful:

* [What is torchelastic?](../../README.md)
* [Quickstart on AWS](../../aws/README.md)
* [Usage](../../USAGE.md)
* [Examples](../../examples/README.md)
* API documentation
    * [Overview](../../USAGE.md)
    * [Rendezvous documentation](../../torchelastic/rendezvous/README.md)
    * [Checkpointing documentation](../../torchelastic/checkpoint/README.md)
* [Configuring](../../USAGE.md#configuring)

  
### Question
I'm a bit confused as the to the proper method to run Torch Elastic on Kubernetes:
- There are instructions at this location https://github.com/pytorch/elastic/tree/master/examples/kubernetes/native which use EFS for checkpointing, load training code from s3, and it looks like it uses the image `torchelastic/examples:0.1.0rc1`

- Then there are also separate instructions at this location https://github.com/pytorch/elastic/tree/master/kubernetes which seem to store checkpoints in the container's FS, seems to be getting the training code from the image it's running, and uses the image 0.2.0rc1

I'm a bit confused as to which set of instructions I should use, and in addition for the first one can't seem to find the place in code where the training code is pulled from s3. Could someone shed some light?

**Comment by kiukchung** [comment]
Apologies for the confusion. https://github.com/pytorch/elastic/tree/master/examples/kubernetes/native is deprecated and scheduled for deletion. Please follow the link to the README in http://pytorch.org/elastic/0.2.0rc0/kubernetes.html.

Closing, feel free to re-open if things are still ambiguous.

**Comment by mttcnnff** [comment]
@kiukchung Thanks for the clarification, all good now!

BTW is the preferred workflow to have training code in the image you pull to run, or download from some external source like s3? Just looking for guidance.

**Comment by kiukchung** [comment]
@mttcnnff sounds good, thanks for reporting. For production use-cases you'd want to have your CI/CD pipeline produce a docker image that is versioned and contains the tested and vetted code. This keeps things sane in terms of operational stability and debuggability.

I'm going to assume you are using AWS:

For experimentation, you want fast iteration hence having a utility launcher that uploads your script to S3 (or makes a commit onto a git branch) then have the docker's entry point pull the code is reasonable. You could also build a dev image with the prod image as the base + your code and push that into a dev ECR registry and instruct k8s to use your dev image from ECR.

**Comment by mttcnnff** [comment]
@kiukchung seems reasonable! Thanks for the pointers, love what you're working on! 🙏
