### ISSUE TITLE
pip install torchelastic fails looking for torch 1.5

### ISSUE THREAD

**Issue by mttcnnff** [pytorch/elastic#95]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our documentation. Here
are some links that may be helpful:

* [What is torchelastic?](../../README.md)
* [Quickstart on AWS](../../aws/README.md)
* [Usage](../../USAGE.md)
* [Examples](../../examples/README.md)
* API documentation
    * [Overview](../../USAGE.md)
    * [Rendezvous documentation](../../torchelastic/rendezvous/README.md)
    * [Checkpointing documentation](../../torchelastic/checkpoint/README.md)
* [Configuring](../../USAGE.md#configuring)

  
### Question
I might be missing something, however when I follow the install instructions on the README of the repo it indicates to install with `pip install torchelastic` however when I do so I get the following error:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/17532157/79495362-7d58b480-7ff2-11ea-9f84-94667c78bc6b.png">

I even tried following the steps found in dockerhub for how you install torch on the 0.2.0rc1 image 
`/bin/sh -c pip uninstall -y -qqq torch`
`/bin/sh -c pip install --progress-bar off --pre torch -f https://download.pytorch.org/whl/test/cu101/torch_test.html`

and still was met with the same error.

I'm trying to use this to test some stuff locally, just wondering what I could do to remedy this.

**Comment by kiukchung** [comment]
Please install torch-1.5.0 nightly by following the instructions here:
https://github.com/pytorch/elastic/blob/master/requirements.txt#L3

This is temporary and we will be switching to torch-1.5.0 proper when it is released.

**Comment by mttcnnff** [comment]
Thanks! Didn't see that
